In [1]:
# make sure to run this pip intall if first time using API
# pip install full_fred

# Caution: get_series_df() may take a couple minutes to run so be patient!

Just a general note about working with API's. Be patient with them! They do have to contact the other application so does take time to retrieve so don't rush it. Rushing it can cause the API to believe you're a bot and flag you so you can't use the API anymore. Just wait lol

In [2]:
import pandas as pd
from full_fred.fred import Fred

In [3]:
#start new environment with the txt file with API key in it
#change the filepath to where your PERSONAL API is. Don't leak this out or else someone else will use it!

#to get filepath on mac, go to the folder where your API is and right click, press option 'Get __ as pathname'

fred = Fred('/Users/victhaaa/fred_api_key.txt')

In [4]:
#shows the api key file
fred.get_api_key_file()

'/Users/victhaaa/fred_api_key.txt'

In [5]:
#example PPI index of all commodities
df = fred.get_series_df('PPIFDG')

In [6]:
df

    realtime_start realtime_end        date    value
0       2022-01-30   2022-01-30  2009-11-01    100.0
1       2022-01-30   2022-01-30  2009-12-01    100.2
2       2022-01-30   2022-01-30  2010-01-01    101.5
3       2022-01-30   2022-01-30  2010-02-01    100.9
4       2022-01-30   2022-01-30  2010-03-01    102.2
..             ...          ...         ...      ...
141     2022-01-30   2022-01-30  2021-08-01  128.296
142     2022-01-30   2022-01-30  2021-09-01  129.342
143     2022-01-30   2022-01-30  2021-10-01  130.767
144     2022-01-30   2022-01-30  2021-11-01  131.736
145     2022-01-30   2022-01-30  2021-12-01  130.941

[146 rows x 4 columns]

In [7]:
df = df.drop(columns = ['realtime_start','realtime_end'], axis = 1)
df

           date    value
0    2009-11-01    100.0
1    2009-12-01    100.2
2    2010-01-01    101.5
3    2010-02-01    100.9
4    2010-03-01    102.2
..          ...      ...
141  2021-08-01  128.296
142  2021-09-01  129.342
143  2021-10-01  130.767
144  2021-11-01  131.736
145  2021-12-01  130.941

[146 rows x 2 columns]

In [8]:
df.set_index('date')

              value
date
2009-11-01    100.0
2009-12-01    100.2
2010-01-01    101.5
2010-02-01    100.9
2010-03-01    102.2
...             ...
2021-08-01  128.296
2021-09-01  129.342
2021-10-01  130.767
2021-11-01  131.736
2021-12-01  130.941

[146 rows x 1 columns]

In [9]:
#atttempting to create dataframe that adds all API fetches
def fetch_data(series_dict):
    #input is a list of series id strings
    full_df = pd.DataFrame()
    
    for key,value in series_dict.items():
        #get the series dataframe
        mini_df = fred.get_series_df(key)
        
        #drop the columns of the retrieved dataframe
        mini_df = mini_df.drop(columns = ['realtime_start','realtime_end'], axis = 1)
        
        mini_df = mini_df.set_index('date')
        mini_df = mini_df.rename(columns = {'value':value})
        
        #wont append with indexes so used columns
        mini_dfT = mini_df.T
        
        full_df = full_df.append(mini_dfT)
    return full_df

In [10]:
#dictionary of series that we need to retrieve
retrieve_series = {'PPIFID':'Final demand','PPIFDG':'Final demand goods',
                   'PPIFDF':'Final demand foods','WPU0111':'Fresh fruits and melons',
                    'WPU0113':'Fresh and dry vegetables','WPU012':'Grains','WPU017107':'Eggs for fresh use'}

In [13]:
retrieve_all_series = {'PPIFID': 'Final demand','PPIFDG': 'Final demand goods',
                       'PPIFDF': 'Final demand foods', 'WPU0111': 'Fresh fruits and melons',
                       'WPU0113': 'Fresh and dry vegetables', 'WPU012': 'Grains',
                       'WPU017107': 'Eggs for fresh use', 'WPU0183': 'Oilseeds',
                       'WPU0211': 'Bakery products', 'WPU021302': 'Milled rice',
                       'WPU021402': 'Pasta products', 'WPU022101': 'Beef and veal',
                       'WPU022104': 'Pork', 'WPU022203': 'Processed young chickens',
                       'WPU022206': 'Processed turkeys', 'WPU0223': 'Finfish and shellfish',
                       'WPU023': 'Dairy products', 'WPU024': 'Processed fruits and vegetables',
                       'WPU0255': 'Confectionery end products', 'WPU0262': 'Soft drinks',
                       'WPU02630104': 'Roasted coffee', 'WPU0278': 'Shortening and cooking oils',
                       'WPU0285': 'Frozen specialty food', 'PPIFDE': 'Final demand energy',
                       'WPU0532': 'Liquefied petroleum gas', 'WPU0541': 'Residential electric power',
                       'WPU0551': 'Residential natural gas', 'WPU0571': 'Gasoline',
                       'WPU057302': 'Home heating oil and distillates', 'WPU057303': 'No. 2 diesel fuel',
                       'WPUFD413': 'Final demand goods less foods and energy',
                       'WPU0261': 'Alcoholic beverages', 'WPU029402': 'Pet food',
                       'WPU038106': "Women's, girls', and infants' apparel",
                       'WPU038107': "Men's and boys' apparel", 'WPU0382': 'Textile housefurnishings',
                       'WPU043': 'Footwear', 'WPU061': 'Industrial chemicals',
                       'WPU0638': 'Pharmaceutical preparations', 'WPU0671': 'Soaps and detergents',
                       'WPU0672': 'Cleaning and polishing products',
                       'WPU0675': 'Cosmetics and other toiletries', 'WPU071201': 'Tires',
                       'WPU072B': 'Consumer, institutional, and commercial products, n.e.c.',
                       'WPU091501': 'Sanitary paper products',
                       'WPUSI021012': 'Agricultural machinery and equipment',
                       'WPU112': 'Construction machinery and equipment',
                       'WPU1137': 'Metal cutting machine tools',
                       'WPU1138': 'Metal forming machine tools',
                       'WPU1139': 'Tools, dies, jigs, fixtures, and industrial molds',
                       'WPU1141': 'Pumps, compressors, and equipment',
                       'WPU1144': 'Industrial material handling equipment',
                       'WPU115': 'Electronic computers and computer equipment',
                       'WPU1162': 'Textile machinery and equipment','WPU1164': 'Paper industries machinery',
                       'WPU1165': 'Printing trades machinery and equipment',
                       'WPU1174': 'Transformers and power regulators',
                       'WPU1176': 'Communication and related equipment',
                       'WPU1178': 'Electronic components and accessories',
                       'WPU117905': 'X-ray and electromedical equipment',
                       'WPU1191': 'Oil field and gas field machinery',
                       'WPU1192': 'Mining machinery and equipment',
                       'WPU1193': 'Office and store machines and equipment','WPU121': 'Household furniture',
                       'WPU122': 'Commercial furniture','WPU123': 'Floor coverings',
                       'WPU124': 'Household appliances','WPU125': 'Home electronic equipment',
                       'WPU1266': 'Silverware and hollowware','WPU126A': 'Lawn and garden equipment excl. garden tractors',
                       'WPU141101': 'Passenger cars','WPU141105': 'Light motor trucks',
                       'WPU141106': 'Heavy motor trucks','WPU1412': 'Motor vehicles parts',
                       'WPU1414': 'Truck trailers','WPU1416': 'Travel trailers and campers',
                       'WPU1421': 'Aircraft','WPU1431': 'Ships','WPU144': 'Railroad equipment',
                       'WPU1511': "Toys, games, and children's vehicles",
                       'WPU1512': 'Sporting and athletic goods','WPU1521': 'Cigarettes',
                       'WPU155': 'Mobile homes','WPU156': 'Medical, surgical & personal aid devices',
                       'WPU159402': 'Jewelry, platinum and karat gold',
                       'WPU159404': 'Costume jewelry and novelties',
                       'PPIFDS': 'Final demand services','PPIDTS': 'Final demand trade services(4)',
                       'WPU571101': 'Machinery and equipment wholesaling',
                       'WPU572': 'Furnishings wholesaling',
                       'WPU575': 'Chemicals and allied products wholesaling',
                       'WPU576': 'Paper and plastics products wholesaling','WPU577': 'Apparel wholesaling',
                       'WPU578': 'Food and alcohol wholesaling', 'WPS581': 'Food and alcohol retailing', 
                       'WPU58210101': ' Health, beauty, and optical goods retailing', 
                       'WPS583': 'Apparel, jewelry, footwear, and accessories retailing', 
                       'WPU584': 'Computer hardware, software, and supplies retailing', 
                       'WPU585': 'TV, video, and photographic equipment and supplies retailing', 
                       'WPU586': 'Automobiles and automobile parts retailing', 
                       'WPU587': 'Manufactured (mobile) homes retailing', 'WPU588': 'RVs, trailers, and campers retailing', 
                       'WPU589': 'Sporting goods, including boats, retailing', 
                       'WPU58A': 'Lawn, garden, and farm equipment and supplies retailing',
                       'WPU58B': 'Furniture retailing', 'WPU58C': 'Flooring and floor coverings retailing',
                       'WPU58D': 'Hardware, building materials, and supplies retailing',
                       'WPU58E': 'Major household appliances retailing','WPU58F': 'Fuels and lubricants retailing',
                       'WPU58G': 'Cleaning supplies and paper products retailing','WPU58H': 'Book retailing',
                       'PPITAW': 'Final demand transportation and warehousing services',
                       'WPU3011': 'Rail transportation of freight and mail','WPU3012': 'Truck transportation of freight',
                       'WPU3014': 'Air transportation of freight','WPU3016': 'Courier, messenger, and U.S. postal services',
                       'WPU3021': 'Rail transportation of passengers','WPU3022': 'Airline passenger services',
                       'PPITTW': 'Final demand services less trade, transportation, and warehousing',
                       'WPU3311': 'Sales of books','WPU3312': 'Sales and subscriptions of periodicals and newspapers',
                       'WPU342': 'Application software publishing',
                       'WPU361': 'Advertising space sales in periodicals, newspapers, directories, and mailing lists',
                       'WPU3711': 'Residential wired telecommunication services',
                       'WPU3721': 'Cellular phone and other wireless telecommunication services',
                       'WPU373': 'Cable and satellite subscriber services','WPU374': 'Internet access services',
                       'WPU375': 'Bundled wired telecommunications access services', 'WPU3912': 'Consumer loans (partial)',
                       'WPU392': 'Deposit services (partial)',
                       'WPU393':'Other credit intermediation, incl. trust services (partial)',
                       'WPU401':'Securities brokerage, dealing, investment advice, and related services',
                       'WPU402':'Portfolio management','WPU411101':'Life insurance',
                       'WPU411102':'Disability insurance, including accidental death',
                       'WPU411103':'Health and medical insurance','WPU411104':'Property and casualty insurance',
                       'WPU412':'Annuities','WPU4321':'Residential property sales and leases, brokerage fees and commissions',
                       'WPU441':'Passenger car rental','WPU451':'Legal services',
                       'WPU452102':'Tax preparation and planning',
                       'WPU453':'Architectural and engineering services',
                       'WPU454':'Management, scientific, and technical consulting services',
                       'WPU471':'Arrangement of flights (partial)','WPU472':'Arrangement of vehicle rentals and lodging',
                       'WPU473':'Arrangement of cruises and tours','WPU511101':'Physician care',
                       'WPU511102':'Medical laboratory and diagnostic imaging care',
                       'WPU511103':'Home health and hospice care','WPU511104':'Hospital outpatient care',
                       'WPU511105':'Dental care','WPU512101':'Hospital inpatient care',
                       'WPU512102':'Nursing home care','WPU521':'Computer training school services',
                       'WPU531':'Traveler accommodation services',
                       'WPU54':'Food and beverages for immediate consumption services (partial)',
                       'WPU552':'Motor vehicle repair and maintenance (partial)',
                       'WPU561':'Membership dues and admissions and recreation facility use fees (partial)',
                       'WPU562':'Recreational activity instruction fees (partial)',
                       'WPU563':'Gaming receipts (partial)','WPU60':'Mining services',
                       'PPIFDC':'Final demand construction','WPU801101':'New warehouse building construction',
                       'WPU801102':'New school building construction',
                       'WPU801103':'New office building construction',
                       'WPU801104':'New industrial building construction',
                       'WPU801105':'New health care building construction'}

In [14]:
fetch_data({'PPIFID':'Final demand'})

date,2009-11-01,2009-12-01,2010-01-01,2010-02-01,2010-03-01,2010-04-01,2010-05-01,2010-06-01,2010-07-01,2010-08-01,...,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-07-01,2021-08-01,2021-09-01,2021-10-01,2021-11-01,2021-12-01
Final demand,100.0,99.9,101.0,100.9,101.2,101.6,101.8,101.6,101.7,101.9,...,123.0,124.3,125.5,126.6,127.824,128.755,129.155,130.128,131.002,130.956

In [15]:
ppi = fetch_data(retrieve_all_series)
ppi

date,2009-11-01,2009-12-01,2010-01-01,2010-02-01,2010-03-01,2010-04-01,2010-05-01,2010-06-01,2010-07-01,2010-08-01,...,1946-03-01,1946-04-01,1946-05-01,1946-06-01,1946-07-01,1946-08-01,1946-09-01,1946-10-01,1946-11-01,1946-12-01
Final demand,100.0,99.9,101.0,100.9,101.2,101.6,101.8,101.6,101.7,101.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Final demand goods,100.0,100.2,101.5,100.9,102.2,102.7,102.9,102.3,102.6,102.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Final demand foods,100.0,101.9,102.0,102.1,104.6,104.0,104.2,101.6,102.4,102.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fresh fruits and melons,118.1,134.6,147.9,140.3,134.2,125.1,132.0,109.8,113.7,111.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fresh and dry vegetables,178.2,188.5,165.1,174.1,262.4,235.2,191.8,150.0,164.7,157.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
New warehouse building construction,123.8,123.7,123.5,123.3,123.2,123.3,123.3,123.3,123.6,123.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New school building construction,130.2,130.2,131.1,131.1,131.0,132.0,131.7,131.5,131.4,131.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New office building construction,112.8,112.7,112.7,112.7,112.3,112.3,112.3,112.4,112.5,112.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New industrial building construction,105.5,105.2,105.3,105.2,105.0,105.2,105.2,105.0,105.4,105.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New health care building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#checking for duplicate dates
for i in ppi:
    print(i)

In [17]:
#sort index of years
merged_ppi = ppi.reindex(sorted(ppi.columns), axis=1)
merged_ppi

date,1926-01-01,1926-02-01,1926-03-01,1926-04-01,1926-05-01,1926-06-01,1926-07-01,1926-08-01,1926-09-01,1926-10-01,...,2021-03-01,2021-04-01,2021-05-01,2021-06-01,2021-07-01,2021-08-01,2021-09-01,2021-10-01,2021-11-01,2021-12-01
Final demand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,123.0,124.3,125.5,126.6,127.824,128.755,129.155,130.128,131.002,130.956
Final demand goods,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,121.3,122.3,124.7,126.5,127.472,128.296,129.342,130.767,131.736,130.941
Final demand foods,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,124.9,127.3,131.6,133.4,131.119,133.625,135.746,135.016,136.603,136.156
Fresh fruits and melons,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,133.5,145.9,143.1,146.8,140.425,139.955,139.506,139.661,167.725,158.535
Fresh and dry vegetables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,191.1,174.8,186.0,189.0,183.851,208.056,249.151,291.962,325.555,277.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
New warehouse building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,162.3,165.5,167.0,168.3,172.746,172.916,172.894,195.379,194.808,195.104
New school building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,174.7,176.4,176.8,176.8,180.126,180.251,180.423,190.659,190.885,190.811
New office building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,149.5,150.6,152.4,152.2,154.611,155.137,155.275,164.047,164.529,165.697
New industrial building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,141.0,142.1,142.1,142.4,145.902,146.453,146.777,158.108,158.897,159.766
New health care building construction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,119.8,123.3,123.8,123.8,125.182,125.373,125.757,131.885,132.501,132.570

In [18]:
#transpose to switch columns with rows
merged_ppiT = merged_ppi.T
merged_ppiT

,Final demand,Final demand goods,Final demand foods,Fresh fruits and melons,Fresh and dry vegetables,Grains,Eggs for fresh use,Oilseeds,Bakery products,Milled rice,...,Membership dues and admissions and recreation facility use fees (partial),Recreational activity instruction fees (partial),Gaming receipts (partial),Mining services,Final demand construction,New warehouse building construction,New school building construction,New office building construction,New industrial building construction,New health care building construction
date,,,,,,,,,,,,,,,,,,,,,
1926-01-01,NaN,NaN,NaN,NaN,NaN,37.9,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-02-01,NaN,NaN,NaN,NaN,NaN,36.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-03-01,NaN,NaN,NaN,NaN,NaN,34.2,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-04-01,NaN,NaN,NaN,NaN,NaN,34.7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1926-05-01,NaN,NaN,NaN,NaN,NaN,33.7,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-01,128.755,128.296,133.625,139.955,208.056,251.986,134.702,258.036,295.061,146.409,...,126.975,121.104,109.567,226.724,137.013,172.916,180.251,155.137,146.453,125.373
2021-09-01,129.155,129.342,135.746,139.506,249.151,223.168,163.239,239.547,298.250,145.840,...,126.496,121.104,110.033,227.694,137.349,172.894,180.423,155.275,146.777,125.757
2021-10-01,130.128,130.767,135.016,139.661,291.962,217.942,143.448,226.417,298.798,146.348,...,128.305,121.104,111.465,229.858,145.638,195.379,190.659,164.047,158.108,131.885
2021-11-01,131.002,131.736,136.603,167.725,325.555,232.633,135.498,226.813,302.243,147.968,...,129.409,121.104,115.349,229.541,146.060,194.808,190.885,164.529,158.897,132.501
2021-12-01,130.956,130.941,136.156,158.535,277.685,246.703,198.984,235.598,303.713,148.135,...,130.921,121.104,109.519,230.741,146.528,195.104,190.811,165.697,159.766,132.570

In [ ]:
mer